version: '3.9'
services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env
    volumes:
      - backend_data:/app/data
    ports:
      - "4000:4000"
  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "5173:80"
volumes:
  backend_data:

